// Generated by CoffeeScript 1.10.0
(function() {
  var crypto, key, key_iteration_count, password, username;

  crypto = require('crypto');

  password = "toto32toto32";

  username = "ben@sonadresse.com";

  key_iteration_count = 5000;

  debugger;

  key = crypto.pbkdf2Sync(password, username, key_iteration_count, 32, 'sha256');

  console.log("key", key, key.toString('hex'));

}).call(this);

//# sourceMappingURL=test-crypto.js.map
